env: "prod"

http_server:
  address: "0.0.0.0"
  port: 8080
  timeout: 30s
  idle_timeout: 120s
  read_timeout: 30s
  write_timeout: 30s

db_postgres:
  host: "db_postgres_prod"
  port: 5432
  user: "flour_admin"
  dbname: "flour_db"
  ssl_mode: "disable" # Should be "require"
#  max_open_conns: 50        # LIMITS
#  max_idle_conns: 10         # LIMITS
#  conn_max_lifetime: 30m     # LIMITS

ws_server:
  address: "0.0.0.0"
  port: 8081
  read_buffer_size: 2048
  write_buffer_size: 2048
  ping_interval: 30s
#    enable_compression: true

cors:
  allowed_origins:
    - "http://localhost:80"
    - "http://127.0.0.1:80"
    - "http://localhost:5173"
    - "http://localhost:8080"
    - "http://localhost:3000"
    - "http://127.0.0.1:50151"
