// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMaterialStorage creates a new instance of MockMaterialStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaterialStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaterialStorage {
	mock := &MockMaterialStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMaterialStorage is an autogenerated mock type for the MaterialStorage type
type MockMaterialStorage struct {
	mock.Mock
}

type MockMaterialStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaterialStorage) EXPECT() *MockMaterialStorage_Expecter {
	return &MockMaterialStorage_Expecter{mock: &_m.Mock}
}
